name: tsyproject
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_auth: ^5.2.0
  dynamic_color: ^1.7.0
  google_maps_flutter: ^2.8.0
  geolocator: ^12.0.0
  cloud_firestore: ^5.5.1
  http: ^1.2.2


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/