// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvd3tuubTnC5m2mvwbJnyUy46vtIh313A',
    appId: '1:403105778000:web:acfb229cf735415f558455',
    messagingSenderId: '403105778000',
    projectId: 'tsyproject-1743d',
    authDomain: 'tsyproject-1743d.firebaseapp.com',
    storageBucket: 'tsyproject-1743d.firebasestorage.app',
    measurementId: 'G-F183W7GSRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs-Cz-tElOHEh2SfpCRv3MK7gQPhDnE6Y',
    appId: '1:403105778000:android:c03f86ff88109d27558455',
    messagingSenderId: '403105778000',
    projectId: 'tsyproject-1743d',
    storageBucket: 'tsyproject-1743d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe2iUOt6g3RPDBHtolhODzq2H-Ott04RA',
    appId: '1:403105778000:ios:0f473e82c8ddfb1d558455',
    messagingSenderId: '403105778000',
    projectId: 'tsyproject-1743d',
    storageBucket: 'tsyproject-1743d.firebasestorage.app',
    iosBundleId: 'com.example.tsyproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe2iUOt6g3RPDBHtolhODzq2H-Ott04RA',
    appId: '1:403105778000:ios:0f473e82c8ddfb1d558455',
    messagingSenderId: '403105778000',
    projectId: 'tsyproject-1743d',
    storageBucket: 'tsyproject-1743d.firebasestorage.app',
    iosBundleId: 'com.example.tsyproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvd3tuubTnC5m2mvwbJnyUy46vtIh313A',
    appId: '1:403105778000:web:5c3e05eac500a5a2558455',
    messagingSenderId: '403105778000',
    projectId: 'tsyproject-1743d',
    authDomain: 'tsyproject-1743d.firebaseapp.com',
    storageBucket: 'tsyproject-1743d.firebasestorage.app',
    measurementId: 'G-C1DLBX8FSH',
  );
}
